---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "false"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: final-group
    alb.ingress.kubernetes.io/subnets: final-pub-a, final-pub-b, final-pub-c
spec:
  ingressClassName: alb
  rules:
    - host: nginx-service-gitops-operator.apps.team1.team1.reca3.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8080 # 32000
