---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  annotations:
    openshift.io/host.generated: "true"
spec:
  selector:
    app: tomcat
  ports:
    - port: 8080 # 서비스가 생성할 포트
      targetPort: 8080 # 서비스가 접근할 pod의 포트
      protocol: TCP
#  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: tomcat
  name: tomcat-service
spec:
  host: tomcat-service-gitops-operator.apps.team1.team1.reca3.local
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tomcat-service
